// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	service "github.com/jwenz723/logwrapper/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	SumEndpoint      endpoint.Endpoint
	MultiplyEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.LogwrapperService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		MultiplyEndpoint: MakeMultiplyEndpoint(s),
		SumEndpoint:      MakeSumEndpoint(s),
	}
	for _, m := range mdw["Sum"] {
		eps.SumEndpoint = m(eps.SumEndpoint)
	}
	for _, m := range mdw["Multiply"] {
		eps.MultiplyEndpoint = m(eps.MultiplyEndpoint)
	}
	return eps
}
